// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuqxwhfzuhxvukcnmdgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1cXh3aGZ6dWh4dnVrY25tZGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjc0MzIsImV4cCI6MjA2NDUwMzQzMn0.Pv7Fxy5_18tjFfF5sFAyrVq2YfLmPT6DPhA6vQthkfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);